### ISSUE TITLE
Start with windows and start minimized

### ISSUE THREAD

**Issue by kodifan** [Darren80/AsusFanControlEnhanced#1]
Hello
I like your fork its working quite good (early releases had a big cpu usage but now its fine)
But i think this program should start with windows and should start minimized to tray
I know it can be achieved other way but it will be handy if it will be implemented.    

PS actually BrightenedDay has already implemented such options in his fork 
https://github.com/BrightenedDay/AsusFanControl
So combination of  those two forks will result if perfect application :)

**Comment by Darren80** [comment]
That is a very good idea. Indeed that will be in the next version, coming out today.
