### ISSUE TITLE
Control yielded to system when temperature is outside range when autostart with windows

### ISSUE THREAD

**Issue by kodifan** [Darren80/AsusFanControlEnhanced#6]
Hello
I think there is something wrong with this autostart option. 
When I set it to autostart I always get this message. 

![image](https://github.com/Darren80/AsusFanControlEnhanced/assets/7819312/4077260b-c9ec-4f30-bca6-64b185f9a4a2)

And no matter how long I wait and what option i change - automatic control of fan is not working - its controlled by the system.

I have suspicion that on start in early stage something is not fully initialized and temp readout is either unavailable,  negative or very large number (i saw it once, temp was like 2894949494 or something)

 When i close program and start it manually everything works as expected.

**Comment by Darren80** [comment]
Hey there and thank you for reaching out.

Was it just CPU temp which was stuck at zero, did fan rpm have any unexpected values or was it just blank? 
I did just encounter the same issue so its not just you, it is peculiar one.

Maybe when the system returns values that are too far off kilter I will restart the application.

**Comment by kodifan** [comment]
hello
it was like on attached screenshot (temp was 0 and fan was empty)
strange - but it's ok now
anyway i think its best to make some delay after program is started (like 5 sek)

**Comment by Darren80** [comment]
I hope the new version fixes the issue for you :)
